title: m4zl.net
description: Mazl´s CV.
baseurl: ""
url: https://m4zl.github.io

remote_theme: piazzai/cvless

# site settings
taglong: 
tagshort: 

# author settings
author:
  name: Place Holder
  email: username@domain.com
photo: assets/banner.png
address: Foobar Hall 1.23
phone: +1 234 567 890

# social media links
social:
  github: username
  instagram: username
  linkedin: username
  stackoverflow: 0000000/username
  x: username
  {% include svg/discord.svg %}
# build settings
permalink: pretty
exclude:
  - docker-compose.yml
  - LICENSE
  - README.md

plugins:
  - jekyll-remote-theme
