site_name: Mazl`s Knowledgebase
site_url: https://m4zl.github.io/
theme: 
  name: readthedocs
  features:
  highlightjs: true
  prev_next_buttons_location: none
  hljs_languages:
    - yaml
    - rust
    - powershell
    - DOS
  locale: de

markdown_extensions:
  - toc:
      permalink: "⚓"

nav:
  - home: 'index.md'
  - 'knowledgebase':
    - 'microsoft': 
      - 'office': 'kb/ms/msoffice.md'
    - 'dell':
      - 'dockingstationen': 'kb/dell/delldocks.md'
  - 'about': 'about.md'