site_name: Mazl`s Index
site_url: https://m4zl.github.io/
theme: 
  name: material
  favicon: media/mazlbeer.png
  logo: media/mazlbeer.png
  language: de
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: 'Josefine Sans'
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    #- navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    #- toc.integrate
    - navigation.top
    - content.code.copy
    - content.code.select
    - content.tabs.link 

markdown_extensions:
  - toc:
      permalink: "⚓"
  - abbr
  - admonition
  - attr_list
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.superfences


plugins:
  - search

nav:
  - Home: 'index.md'
  - 'IT - Wissendatenbank':
    - kb/index.md
    - 'Dell':
      - 'Dockingstationen': 'kb/dell/delldocks.md'
    - 'Microsoft':
      - kb/ms/index.md
      - 'Office': 'kb/ms/msoffice.md'
  - Spiele: gaming/index.md
  - 'About': 'about.md'