site_name: Mazl`s Knowledgebase
site_url: https://m4zl.github.io/
theme: 
  name: terminal
  features:
    - navigation.side.indexes
  highlightjs: true
  prev_next_buttons_location: none
  hljs_languages:
    - yaml
    - rust
    - powershell
    - DOS
  locale: de

markdown_extensions:
  - toc:
      baselevel: "0"
      toc_depth: "1"
      permalink: "permalink"

nav:
  - home: 'index.md'
  - knowledgebase:
    - 'microsoft': 
      - index: 'kb/ms/index.md'
      - 'office': 'kb/ms/msoffice.md'
    - 'dell':
      - index: 'kb/dell/index.md'
      - 'dockingstationen': 'kb/dell/delldocks.md'
  - 'about': 'about.md'